export const ORDER_EMAIL_NOTIFICATION_REQUEST =
  "ORDER_EMAIL_NOTIFICATION_REQUEST";
export const ORDER_EMAIL_NOTIFICATION_SUCCESS =
  "ORDER_EMAIL_NOTIFICATION_SUCCESS";
export const ORDER_EMAIL_NOTIFICATION_FAIL = "ORDER_EMAIL_NOTIFICATION_FAIL";
export const ORDER_EMAIL_NOTIFICATION_RESET = "ORDER_EMAIL_NOTIFICATION_RESET";
