export const KYC_VERIFY_EMAIL_REQUEST = "KYC_VERIFY_EMAIL_REQUEST";
export const KYC_VERIFY_EMAIL_SUCCESS = "KYC_VERIFY_EMAIL_SUCCESS";
export const KYC_VERIFY_EMAIL_FAIL = "KYC_VERIFY_EMAIL_FAIL";
export const KYC_VERIFY_EMAIL_RESET = "KYC_VERIFY_EMAIL_RESET";

export const KYC_VERIFY_CODE_REQUEST = "KYC_VERIFY_CODE_REQUEST";
export const KYC_VERIFY_CODE_SUCCESS = "KYC_VERIFY_CODE_SUCCESS";
export const KYC_VERIFY_CODE_FAIL = "KYC_VERIFY_CODE_FAIL";
export const KYC_VERIFY_CODE_RESET = "KYC_VERIFY_CODE_RESET";

export const KYC_PERSONAL_INFO_REQUEST = "KYC_PERSONAL_INFO_REQUEST";
export const KYC_PERSONAL_INFO_SUCCESS = "KYC_PERSONAL_INFO_SUCCESS";
export const KYC_PERSONAL_INFO_FAIL = "KYC_PERSONAL_INFO_FAIL";
export const KYC_PERSONAL_INFO_RESET = "KYC_PERSONAL_INFO_RESET";

export const KYC_CONTACT_INFO_REQUEST = "KYC_CONTACT_INFO_REQUEST";
export const KYC_CONTACT_INFO_SUCCESS = "KYC_CONTACT_INFO_SUCCESS";
export const KYC_CONTACT_INFO_FAIL = "KYC_CONTACT_INFO_FAIL";
export const KYC_CONTACT_INFO_RESET = "KYC_CONTACT_INFO_RESET";

export const KYC_COMPANY_INFO_REQUEST = "KYC_COMPANY_INFO_REQUEST";
export const KYC_COMPANY_INFO_SUCCESS = "KYC_COMPANY_INFO_SUCCESS";
export const KYC_COMPANY_INFO_FAIL = "KYC_COMPANY_INFO_FAIL";
export const KYC_COMPANY_INFO_RESET = "KYC_COMPANY_INFO_RESET";

export const KYC_DOCUMENT_FILE_REQUEST = "KYC_DOCUMENT_FILE_REQUEST";
export const KYC_DOCUMENT_FILE_SUCCESS = "KYC_DOCUMENT_FILE_SUCCESS";
export const KYC_DOCUMENT_FILE_FAIL = "KYC_DOCUMENT_FILE_FAIL";
export const KYC_DOCUMENT_FILE_RESET = "KYC_DOCUMENT_FILE_RESET";

export const KYC_DISPLAY_PICTURE_REQUEST = "KYC_DISPLAY_PICTURE_REQUEST";
export const KYC_DISPLAY_PICTURE_SUCCESS = "KYC_DISPLAY_PICTURE_SUCCESS";
export const KYC_DISPLAY_PICTURE_FAIL = "KYC_DISPLAY_PICTURE_FAIL";
export const KYC_DISPLAY_PICTURE_RESET = "KYC_DISPLAY_PICTURE_RESET";
