export const GET_USER_PAYMENTS_REQUEST = "GET_USER_PAYMENTS_REQUEST";
export const GET_USER_PAYMENTS_SUCCESS = "GET_USER_PAYMENTS_SUCCESS";
export const GET_USER_PAYMENTS_FAIL = "GET_USER_PAYMENTS_FAIL";
export const GET_USER_PAYMENTS_RESET = "GET_USER_PAYMENTS_RESET";

export const GET_USER_PAYMENTS_BYID_REQUEST = "GET_USER_PAYMENTS_BYID_REQUEST";
export const GET_USER_PAYMENTS_BYID_SUCCESS = "GET_USER_PAYMENTS_BYID_SUCCESS";
export const GET_USER_PAYMENTS_BYID_FAIL = "GET_USER_PAYMENTS_BYID_FAIL";
export const GET_USER_PAYMENTS_BYID_RESET = "GET_USER_PAYMENTS_BYID_RESET";

export const INITIALIZE_PAYMENTS_REQUEST = "INITIALIZE_PAYMENTS_REQUEST";
export const INITIALIZE_PAYMENTS_SUCCESS = "INITIALIZE_PAYMENTS_SUCCESS";
export const INITIALIZE_PAYMENTS_FAIL = "INITIALIZE_PAYMENTS_FAIL";
export const INITIALIZE_PAYMENTS_RESET = "INITIALIZE_PAYMENTS_RESET";

export const VERIFY_PAYMENTS_REQUEST = "VERIFY_PAYMENTS_REQUEST";
export const VERIFY_PAYMENTS_SUCCESS = "VERIFY_PAYMENTS_SUCCESS";
export const VERIFY_PAYMENTS_FAIL = "VERIFY_PAYMENTS_FAIL";
export const VERIFY_PAYMENTS_RESET = "VERIFY_PAYMENTS_RESET";
