export const USER_GET_PRODUCTS_REQUEST = "USER_GET_PRODUCTS_REQUEST";
export const USER_GET_PRODUCTS_SUCCESS = "USER_GET_PRODUCTS_SUCCESS";
export const USER_GET_PRODUCTS_FAIL = "USER_GET_PRODUCTS_FAIL";
export const USER_GET_PRODUCTS_RESET = "USER_GET_PRODUCTS_RESET";

export const USER_GET_NEW_PRODUCTS_REQUEST = "USER_GET_NEW_PRODUCTS_REQUEST";
export const USER_GET_NEW_PRODUCTS_SUCCESS = "USER_GET_NEW_PRODUCTS_SUCCESS";
export const USER_GET_NEW_PRODUCTS_FAIL = "USER_GET_NEW_PRODUCTS_FAIL";
export const USER_GET_NEW_PRODUCTS_RESET = "USER_GET_NEW_PRODUCTS_RESET";

export const USER_GET_TOP_RATED_PRODUCTS_REQUEST =
  "USER_GET_TOP_RATED_PRODUCTS_REQUEST";
export const USER_GET_TOP_RATED_PRODUCTS_SUCCESS =
  "USER_GET_TOP_RATED_PRODUCTS_SUCCESS";
export const USER_GET_TOP_RATED_PRODUCTS_FAIL =
  "USER_GET_TOP_RATED_PRODUCTS_FAIL";
export const USER_GET_TOP_RATED_PRODUCTS_RESET =
  "USER_GET_TOP_RATED_PRODUCTS_RESET";

export const USER_GET_PRODUCT_BY_ID_REQUEST = "USER_GET_PRODUCT_BY_ID_REQUEST";
export const USER_GET_PRODUCT_BY_ID_SUCCESS = "USER_GET_PRODUCT_BY_ID_SUCCESS";
export const USER_GET_PRODUCT_BY_ID_FAIL = "USER_GET_PRODUCT_BY_ID_FAIL";
export const USER_GET_PRODUCT_BY_ID_RESET = "USER_GET_PRODUCT_BY_ID_RESET";

export const USER_GET_PRODUCTS_CATEGORY_REQUEST =
  "USER_GETBYPRODUCTS_CATEGORY_REQUEST";
export const USER_GET_PRODUCTS_CATEGORY_SUCCESS =
  "USER_GETBYPRODUCTS_CATEGORY_SUCCESS";
export const USER_GET_PRODUCTS_CATEGORY_FAIL =
  "USER_GETBYPRODUCTS_CATEGORY_FAIL";
export const USER_GET_PRODUCTS_CATEGORY_RESET = "USER_GETBYALL_CATEGORY_RESET";
