export const CREATE_TESTIMONIAL_REQUEST = "CREATE_TESTIMONIAL_REQUEST";
export const CREATE_TESTIMONIAL_SUCCESS = "CREATE_TESTIMONIAL_SUCCESS";
export const CREATE_TESTIMONIAL_FAIL = "CREATE_TESTIMONIAL_FAIL";
export const CREATE_TESTIMONIAL_RESET = "CREATE_TESTIMONIAL_RESET";
