export { default as bgExterior } from "./bg-exterior.png";
export { default as ExteriorCamera } from "./exterior-camera.png";
export { default as ExteriorEarpiece } from "./exterior-earpiece.png";
export { default as ExteriorEarpiece2 } from "./exterior-earpiece2.png";
export { default as ExteriorJug } from "./exterior-jug.png";
export { default as ExteriorLaptop } from "./exterior-laptop.png";
export { default as ExteriorPhone } from "./exterior-phone.png";
export { default as ExteriorPhone2 } from "./exterior-phone2.png";
export { default as ExteriorWatch } from "./exterior-watch.png";
