export const SELLER_GET_ANALYSIS_REQUEST = "SELLER_GET_ANALYSIS_REQUEST";
export const SELLER_GET_ANALYSIS_SUCCESS = "SELLER_GET_ANALYSIS_SUCCESS";
export const SELLER_GET_ANALYSIS_FAIL = "SELLER_GET_ANALYSIS_FAIL";
export const SELLER_GET_ANALYSIS_RESET = "SELLER_GET_ANALYSIS_RESET";
