export const SELLER_RESPOND_REVIEW_REQUEST = "SELLER_RESPOND_REVIEW_REQUEST";
export const SELLER_RESPOND_REVIEW_SUCCESS = "SELLER_RESPOND_REVIEW_SUCCESS";
export const SELLER_RESPOND_REVIEW_FAIL = "SELLER_RESPOND_REVIEW_FAIL";
export const SELLER_RESPOND_REVIEW_RESET = "SELLER_RESPOND_REVIEW_RESET";
