export const SELLER_CREATE_SERVICE_REQUEST = "SELLER_CREATE_SERVICE_REQUEST";
export const SELLER_CREATE_SERVICE_SUCCESS = "SELLER_CREATE_SERVICE_SUCCESS";
export const SELLER_CREATE_SERVICE_FAIL = "SELLER_CREATE_SERVICE_FAIL";
export const SELLER_CREATE_SERVICE_RESET = "SELLER_CREATE_SERVICE_RESET";

export const SELLER_UPDATE_SERVICE_REQUEST = "SELLER_UPDATE_SERVICE_REQUEST";
export const SELLER_UPDATE_SERVICE_SUCCESS = "SELLER_UPDATE_SERVICE_SUCCESS";
export const SELLER_UPDATE_SERVICE_FAIL = "SELLER_UPDATE_SERVICE_FAIL";
export const SELLER_UPDATE_SERVICE_RESET = "SELLER_UPDATE_SERVICE_RESET";

export const SELLER_DELETE_SERVICE_REQUEST = "SELLER_DELETE_SERVICE_REQUEST";
export const SELLER_DELETE_SERVICE_SUCCESS = "SELLER_DELETE_SERVICE_SUCCESS";
export const SELLER_DELETE_SERVICE_FAIL = "SELLER_DELETE_SERVICE_FAIL";
export const SELLER_DELETE_SERVICE_RESET = "SELLER_DELETE_SERVICE_RESET";

export const SELLER_GETBYID_SERVICE_REQUEST = "SELLER_GETBYID_SERVICE_REQUEST";
export const SELLER_GETBYID_SERVICE_SUCCESS = "SELLER_GETBYID_SERVICE_SUCCESS";
export const SELLER_GETBYID_SERVICE_FAIL = "SELLER_GETBYID_SERVICE_FAIL";
export const SELLER_GETBYID_SERVICE_RESET = "SELLER_GETBYID_SERVICE_RESET";

export const SELLER_GET_ALL_SERVICE_REQUEST = "SELLER_GETBYALL_SERVICE_REQUEST";
export const SELLER_GET_ALL_SERVICE_SUCCESS = "SELLER_GETBYALL_SERVICE_SUCCESS";
export const SELLER_GET_ALL_SERVICE_FAIL = "SELLER_GETBYALL_SERVICE_FAIL";
export const SELLER_GET_ALL_SERVICE_RESET = "SELLER_GETBYALL_SERVICE_RESET";
