export const SELLER_CREATE_PRODUCT_REQUEST = "SELLER_CREATE_PRODUCT_REQUEST";
export const SELLER_CREATE_PRODUCT_SUCCESS = "SELLER_CREATE_PRODUCT_SUCCESS";
export const SELLER_CREATE_PRODUCT_FAIL = "SELLER_CREATE_PRODUCT_FAIL";
export const SELLER_CREATE_PRODUCT_RESET = "SELLER_CREATE_PRODUCT_RESET";

export const SELLER_UPDATE_PRODUCT_REQUEST = "SELLER_UPDATE_PRODUCT_REQUEST";
export const SELLER_UPDATE_PRODUCT_SUCCESS = "SELLER_UPDATE_PRODUCT_SUCCESS";
export const SELLER_UPDATE_PRODUCT_FAIL = "SELLER_UPDATE_PRODUCT_FAIL";
export const SELLER_UPDATE_PRODUCT_RESET = "SELLER_UPDATE_PRODUCT_RESET";

export const SELLER_DELETE_PRODUCT_REQUEST = "SELLER_DELETE_PRODUCT_REQUEST";
export const SELLER_DELETE_PRODUCT_SUCCESS = "SELLER_DELETE_PRODUCT_SUCCESS";
export const SELLER_DELETE_PRODUCT_FAIL = "SELLER_DELETE_PRODUCT_FAIL";
export const SELLER_DELETE_PRODUCT_RESET = "SELLER_DELETE_PRODUCT_RESET";

export const SELLER_GETBYID_PRODUCT_REQUEST = "SELLER_GETBYID_PRODUCT_REQUEST";
export const SELLER_GETBYID_PRODUCT_SUCCESS = "SELLER_GETBYID_PRODUCT_SUCCESS";
export const SELLER_GETBYID_PRODUCT_FAIL = "SELLER_GETBYID_PRODUCT_FAIL";
export const SELLER_GETBYID_PRODUCT_RESET = "SELLER_GETBYID_PRODUCT_RESET";

export const SELLER_GET_ALL_PRODUCT_REQUEST = "SELLER_GETBYALL_PRODUCT_REQUEST";
export const SELLER_GET_ALL_PRODUCT_SUCCESS = "SELLER_GETBYALL_PRODUCT_SUCCESS";
export const SELLER_GET_ALL_PRODUCT_FAIL = "SELLER_GETBYALL_PRODUCT_FAIL";
export const SELLER_GET_ALL_PRODUCT_RESET = "SELLER_GETBYALL_PRODUCT_RESET";
