export const GET_SELLER_SERVICE_ORDERS_REQUEST =
  "GET_SELLER_SERVICE_ORDERS_REQUEST";
export const GET_SELLER_SERVICE_ORDERS_SUCCESS =
  "GET_SELLER_SERVICE_ORDERS_SUCCESS";
export const GET_SELLER_SERVICE_ORDERS_FAIL = "GET_SELLER_SERVICE_ORDERS_FAIL";
export const GET_SELLER_SERVICE_ORDERS_RESET =
  "GET_SELLER_SERVICE_ORDERS_RESET";
