export const ADD_TO_BROWSE_HISTORY_REQUEST = "ADD_TO_BROWSE_HISTORY_REQUEST";
export const ADD_TO_BROWSE_HISTORY_SUCCESS = "ADD_TO_BROWSE_HISTORY_SUCCESS";
export const ADD_TO_BROWSE_HISTORY_FAIL = "ADD_TO_BROWSE_HISTORY_FAIL";
export const ADD_TO_BROWSE_HISTORY_RESET = "ADD_TO_BROWSE_HISTORY_RESET";

export const VIEW_BROWSE_HISTORY_REQUEST = "VIEW_BROWSE_HISTORY_REQUEST";
export const VIEW_BROWSE_HISTORY_SUCCESS = "VIEW_BROWSE_HISTORY_SUCCESS";
export const VIEW_BROWSE_HISTORY_FAIL = "VIEW_BROWSE_HISTORY_FAIL";
export const VIEW_BROWSE_HISTORY_RESET = "VIEW_BROWSE_HISTORY_RESET";
