export const HOME_PRODUCTS_REQUEST = "HOME_PRODUCTS_REQUEST";
export const HOME_PRODUCTS_SUCCESS = "HOME_PRODUCTS_SUCCESS";
export const HOME_PRODUCTS_FAIL = "HOME_PRODUCTS_FAIL";
export const HOME_PRODUCTS_RESET = "HOME_PRODUCTS_RESET";

export const HOME_SERVICES_REQUEST = "HOME_SERVICES_REQUEST";
export const HOME_SERVICES_SUCCESS = "HOME_SERVICES_SUCCESS";
export const HOME_SERVICES_FAIL = "HOME_SERVICES_FAIL";
export const HOME_SERVICES_RESET = "HOME_SERVICES_RESET";

export const HOME_PRODUCTS_DETAIL_REQUEST = "HOME_PRODUCTS_DETAIL_REQUEST";
export const HOME_PRODUCTS_DETAIL_SUCCESS = "HOME_PRODUCTS_DETAIL_SUCCESS";
export const HOME_PRODUCTS_DETAIL_FAIL = "HOME_PRODUCTS_DETAIL_FAIL";
export const HOME_PRODUCTS_DETAIL_RESET = "HOME_PRODUCTS_DETAIL_RESET";

export const HOME_SERVICES_DETAIL_REQUEST = "HOME_SERVICES_DETAIL_REQUEST";
export const HOME_SERVICES_DETAIL_SUCCESS = "HOME_SERVICES_DETAIL_SUCCESS";
export const HOME_SERVICES_DETAIL_FAIL = "HOME_SERVICES_DETAIL_FAIL";
export const HOME_SERVICES_DETAIL_RESET = "HOME_SERVICES_DETAIL_RESET";

export const HOME_SERVICES_CATEGORY_REQUEST = "HOME_SERVICES_CATEGORY_REQUEST";
export const HOME_SERVICES_CATEGORY_SUCCESS = "HOME_SERVICES_CATEGORY_SUCCESS";
export const HOME_SERVICES_CATEGORY_FAIL = "HOME_SERVICES_CATEGORY_FAIL";
export const HOME_SERVICES_CATEGORY_RESET = "HOME_SERVICES_CATEGORY_RESET";

export const HOME_PRODUCTS_CATEGORY_REQUEST = "HOME_PRODUCTS_CATEGORY_REQUEST";
export const HOME_PRODUCTS_CATEGORY_SUCCESS = "HOME_PRODUCTS_CATEGORY_SUCCESS";
export const HOME_PRODUCTS_CATEGORY_FAIL = "HOME_PRODUCTS_CATEGORY_FAIL";
export const HOME_PRODUCTS_CATEGORY_RESET = "HOME_PRODUCTS_CATEGORY_RESET";
