export const HOME_PRODUCTS_REQUEST = "HOME_PRODUCTS_REQUEST";
export const HOME_PRODUCTS_SUCCESS = "HOME_PRODUCTS_SUCCESS";
export const HOME_PRODUCTS_FAIL = "HOME_PRODUCTS_FAIL";
export const HOME_PRODUCTS_RESET = "HOME_PRODUCTS_RESET";

export const HOME_SERVICES_REQUEST = "HOME_SERVICES_REQUEST";
export const HOME_SERVICES_SUCCESS = "HOME_SERVICES_SUCCESS";
export const HOME_SERVICES_FAIL = "HOME_SERVICES_FAIL";
export const HOME_SERVICES_RESET = "HOME_SERVICES_RESET";

export const HOME_CATEGORIES_REQUEST = "HOME_CATEGORIES_REQUEST";
export const HOME_CATEGORIES_SUCCESS = "HOME_CATEGORIES_SUCCESS";
export const HOME_CATEGORIES_FAIL = "HOME_CATEGORIES_FAIL";
export const HOME_CATEGORIES_RESET = "HOME_CATEGORIES_RESET";
