export const USER_SUBSCRIBE_REQUEST = "USER_SUBSCRIBE_REQUEST";
export const USER_SUBSCRIBE_SUCCESS = "USER_SUBSCRIBE_SUCCESS";
export const USER_SUBSCRIBE_FAIL = "USER_SUBSCRIBE_FAIL";
export const USER_SUBSCRIBE_RESET = "USER_SUBSCRIBESETEST";

export const ADMIN_GET_SUBSCRIBERS_REQUEST = "ADMIN_GET_SUBSCRIBERS_REQUEST";
export const ADMIN_GET_SUBSCRIBERS_SUCCESS = "ADMIN_GET_SUBSCRIBERS_SUCCESS";
export const ADMIN_GET_SUBSCRIBERS_FAIL = "ADMIN_GET_SUBSCRIBERS_FAIL";
export const ADMIN_GET_SUBSCRIBERS_RESET = "ADMIN_GET_SUBSCRIBERSSETEST";
