export const ADMIN_CREATE_CATEGORY_REQUEST = "ADMIN_CREATE_CATEGORY_REQUEST";
export const ADMIN_CREATE_CATEGORY_SUCCESS = "ADMIN_CREATE_CATEGORY_SUCCESS";
export const ADMIN_CREATE_CATEGORY_FAIL = "ADMIN_CREATE_CATEGORY_FAIL";
export const ADMIN_CREATE_CATEGORY_RESET = "ADMIN_CREATE_CATEGORY_RESET";

export const ADMIN_UPDATE_CATEGORY_REQUEST = "ADMIN_UPDATE_CATEGORY_REQUEST";
export const ADMIN_UPDATE_CATEGORY_SUCCESS = "ADMIN_UPDATE_CATEGORY_SUCCESS";
export const ADMIN_UPDATE_CATEGORY_FAIL = "ADMIN_UPDATE_CATEGORY_FAIL";
export const ADMIN_UPDATE_CATEGORY_RESET = "ADMIN_UPDATE_CATEGORY_RESET";

export const ADMIN_DELETE_CATEGORY_REQUEST = "ADMIN_DELETE_CATEGORY_REQUEST";
export const ADMIN_DELETE_CATEGORY_SUCCESS = "ADMIN_DELETE_CATEGORY_SUCCESS";
export const ADMIN_DELETE_CATEGORY_FAIL = "ADMIN_DELETE_CATEGORY_FAIL";
export const ADMIN_DELETE_CATEGORY_RESET = "ADMIN_DELETE_CATEGORY_RESET";

export const ADMIN_GETBYID_CATEGORY_REQUEST = "ADMIN_GETBYID_CATEGORY_REQUEST";
export const ADMIN_GETBYID_CATEGORY_SUCCESS = "ADMIN_GETBYID_CATEGORY_SUCCESS";
export const ADMIN_GETBYID_CATEGORY_FAIL = "ADMIN_GETBYID_CATEGORY_FAIL";
export const ADMIN_GETBYID_CATEGORY_RESET = "ADMIN_GETBYID_CATEGORY_RESET";

export const ADMIN_GET_ALL_CATEGORY_REQUEST = "ADMIN_GETBYALL_CATEGORY_REQUEST";
export const ADMIN_GET_ALL_CATEGORY_SUCCESS = "ADMIN_GETBYALL_CATEGORY_SUCCESS";
export const ADMIN_GET_ALL_CATEGORY_FAIL = "ADMIN_GETBYALL_CATEGORY_FAIL";
export const ADMIN_GET_ALL_CATEGORY_RESET = "ADMIN_GETBYALL_CATEGORY_RESET";

export const ADMIN_GET_SERVICES_CATEGORY_REQUEST =
  "ADMIN_GETBYSERVICES_CATEGORY_REQUEST";
export const ADMIN_GET_SERVICES_CATEGORY_SUCCESS =
  "ADMIN_GETBYSERVICES_CATEGORY_SUCCESS";
export const ADMIN_GET_SERVICES_CATEGORY_FAIL =
  "ADMIN_GETBYSERVICES_CATEGORY_FAIL";
export const ADMIN_GET_SERVICES_CATEGORY_RESET =
  "ADMIN_GETBYALL_CATEGORY_RESET";

export const ADMIN_GET_PRODUCTS_CATEGORY_REQUEST =
  "ADMIN_GETBYPRODUCTS_CATEGORY_REQUEST";
export const ADMIN_GET_PRODUCTS_CATEGORY_SUCCESS =
  "ADMIN_GETBYPRODUCTS_CATEGORY_SUCCESS";
export const ADMIN_GET_PRODUCTS_CATEGORY_FAIL =
  "ADMIN_GETBYPRODUCTS_CATEGORY_FAIL";
export const ADMIN_GET_PRODUCTS_CATEGORY_RESET =
  "ADMIN_GETBYPRODUCTS_CATEGORY_RESET";
