export const ADMIN_CREATE_USER_REQUEST = "ADMIN_CREATE_USER_REQUEST";
export const ADMIN_CREATE_USER_SUCCESS = "ADMIN_CREATE_USER_SUCCESS";
export const ADMIN_CREATE_USER_FAIL = "ADMIN_CREATE_USER_FAIL";
export const ADMIN_CREATE_USER_RESET = "ADMIN_CREATE_USER_RESET";

export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST";
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS";
export const ADMIN_UPDATE_USER_FAIL = "ADMIN_UPDATE_USER_FAIL";
export const ADMIN_UPDATE_USER_RESET = "ADMIN_UPDATE_USER_RESET";

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL";
export const ADMIN_DELETE_USER_RESET = "ADMIN_DELETE_USER_RESET";

export const ADMIN_GETBYID_USER_REQUEST = "ADMIN_GETBYID_USER_REQUEST";
export const ADMIN_GETBYID_USER_SUCCESS = "ADMIN_GETBYID_USER_SUCCESS";
export const ADMIN_GETBYID_USER_FAIL = "ADMIN_GETBYID_USER_FAIL";
export const ADMIN_GETBYID_USER_RESET = "ADMIN_GETBYID_USER_RESET";

export const ADMIN_GET_ALL_USERS_REQUEST = "ADMIN_GETBYALL_USER_REQUEST";
export const ADMIN_GET_ALL_USERS_SUCCESS = "ADMIN_GETBYALL_USER_SUCCESS";
export const ADMIN_GET_ALL_USERS_FAIL = "ADMIN_GETBYALL_USER_FAIL";
export const ADMIN_GET_ALL_USERS_RESET = "ADMIN_GETBYALL_USER_RESET";
